server:
  port: 9000

spring:
  application:
    name: line-sdk-mongodb-integration-demo

  data:
    mongodb:
      uri: mongodb://admin:password@localhost:27017/message?authSource=admin
      authentication-database: admin
      auto-index-creation: true
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

line.bot:
  channel-token: G/DWAJgA9y7TCbXKhFYc3BTNUUhFbf+1J43ICekBMaADugB+w7Xd1wMBQAoPl/on4yFB5NkDZ29/7qfRARM7midd6908L7aPek01nkWEP58suvuqgn36buvh1pt1NyhkCmDJkD5hGTmCedsw4MNCxgdB04t89/1O/w1cDnyilFU=
  channel-secret: 2f40e0920de329e7e52da38353df2405
  handler.path: /callback